version: '3'
services:
  web:
    container_name: web
    #build: container/web
    image: nginx:latest
    restart: always
    logging:
      driver: journald
      options:
        tag: docker-service/{{.Name}}/{{.ID}}
    ports:
      - 80:80
    volumes:
      - ./container/web/html:/usr/share/nginx/html
    networks:
      - my-network1
  db:
    container_name: db
    #build: container/db
    image: mariadb
    restart: always
    networks:
      - my-network1
  php:
    container_name: php
    build: container/php
    restart: always
    networks:
      - my-network1
networks:
  my-network1: